services:
  - type: web
    name: expense-backend
    env: java
    rootDir: Backend
    plan: free
    buildCommand: chmod +x mvnw && ./mvnw clean package
    startCommand: java -jar target/expense-backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: MONGODB_URI
        sync: false

